import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const fiveMonthsAgo = new Date();
    fiveMonthsAgo.setMonth(fiveMonthsAgo.getMonth() - 5);
    const timestamp = fiveMonthsAgo.toISOString();

    const sampleProducts = [
        // Raw Materials (category 1)
        {
            name: 'Steel Sheets',
            sku: 'RM-STEEL-001',
            categoryId: 1,
            unitOfMeasure: 'kg',
            reorderLevel: 100,
            currentStock: 250,
            costPrice: 50,
            sellingPrice: 75,
            description: 'High-grade steel sheets for industrial manufacturing and construction applications',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Aluminum Bars',
            sku: 'RM-ALU-002',
            categoryId: 1,
            unitOfMeasure: 'kg',
            reorderLevel: 50,
            currentStock: 30,
            costPrice: 80,
            sellingPrice: 120,
            description: 'Premium aluminum bars with excellent corrosion resistance for various applications',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Copper Wire',
            sku: 'RM-COP-003',
            categoryId: 1,
            unitOfMeasure: 'kg',
            reorderLevel: 75,
            currentStock: 150,
            costPrice: 120,
            sellingPrice: 180,
            description: 'Pure copper wire for electrical and industrial applications with high conductivity',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Finished Goods (category 2)
        {
            name: 'Industrial Pump',
            sku: 'FG-PUMP-001',
            categoryId: 2,
            unitOfMeasure: 'units',
            reorderLevel: 10,
            currentStock: 25,
            costPrice: 500,
            sellingPrice: 800,
            description: 'Heavy-duty industrial pump for fluid transfer and process applications',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Valve Assembly',
            sku: 'FG-VALVE-002',
            categoryId: 2,
            unitOfMeasure: 'units',
            reorderLevel: 20,
            currentStock: 15,
            costPrice: 150,
            sellingPrice: 250,
            description: 'Complete valve assembly for pipeline and industrial control systems',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Pressure Gauge',
            sku: 'FG-GAUGE-003',
            categoryId: 2,
            unitOfMeasure: 'units',
            reorderLevel: 30,
            currentStock: 45,
            costPrice: 75,
            sellingPrice: 120,
            description: 'Precision pressure gauge for monitoring and control in industrial systems',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Tools & Equipment (category 3)
        {
            name: 'Power Drill',
            sku: 'TL-DRILL-001',
            categoryId: 3,
            unitOfMeasure: 'units',
            reorderLevel: 5,
            currentStock: 12,
            costPrice: 200,
            sellingPrice: 350,
            description: 'Professional-grade power drill with variable speed control and multiple attachments',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Welding Machine',
            sku: 'TL-WELD-002',
            categoryId: 3,
            unitOfMeasure: 'units',
            reorderLevel: 3,
            currentStock: 2,
            costPrice: 1500,
            sellingPrice: 2200,
            description: 'Industrial welding machine with advanced features for professional welding applications',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Safety Gloves',
            sku: 'TL-GLOVE-003',
            categoryId: 3,
            unitOfMeasure: 'pairs',
            reorderLevel: 100,
            currentStock: 180,
            costPrice: 10,
            sellingPrice: 18,
            description: 'Heat-resistant safety gloves with reinforced palms for industrial work environments',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Office Supplies (category 4)
        {
            name: 'Copy Paper',
            sku: 'OF-PAPER-001',
            categoryId: 4,
            unitOfMeasure: 'boxes',
            reorderLevel: 50,
            currentStock: 75,
            costPrice: 25,
            sellingPrice: 40,
            description: 'Premium quality A4 copy paper, 500 sheets per box, suitable for all printers',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Printer Ink',
            sku: 'OF-INK-002',
            categoryId: 4,
            unitOfMeasure: 'units',
            reorderLevel: 20,
            currentStock: 18,
            costPrice: 45,
            sellingPrice: 70,
            description: 'High-capacity printer ink cartridges compatible with multiple printer models',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Notebooks',
            sku: 'OF-NOTE-003',
            categoryId: 4,
            unitOfMeasure: 'units',
            reorderLevel: 100,
            currentStock: 200,
            costPrice: 3,
            sellingPrice: 6,
            description: 'Professional spiral-bound notebooks with 200 pages for office and meeting notes',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Electronics (category 5)
        {
            name: 'Circuit Boards',
            sku: 'EL-BOARD-001',
            categoryId: 5,
            unitOfMeasure: 'units',
            reorderLevel: 40,
            currentStock: 60,
            costPrice: 85,
            sellingPrice: 140,
            description: 'Multi-layer printed circuit boards for electronic device assembly and prototyping',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'LED Displays',
            sku: 'EL-LED-002',
            categoryId: 5,
            unitOfMeasure: 'units',
            reorderLevel: 25,
            currentStock: 20,
            costPrice: 120,
            sellingPrice: 200,
            description: 'High-brightness LED display modules with programmable interfaces for various applications',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            name: 'Sensors',
            sku: 'EL-SENS-003',
            categoryId: 5,
            unitOfMeasure: 'units',
            reorderLevel: 50,
            currentStock: 90,
            costPrice: 65,
            sellingPrice: 110,
            description: 'Precision sensors for temperature, pressure, and motion detection in industrial automation',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
    console.log('📦 Created 15 products across 5 categories');
    console.log('⚠️  5 products marked as LOW STOCK (currentStock <= reorderLevel)');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});