import { db } from '@/db';
import { stockLedger } from '@/db/schema';

async function main() {
    const sampleStockLedger = [
        // Receipt REC-2024-001 entries (3 products)
        {
            productId: 1,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-001',
            quantityChange: 100,
            quantityAfter: 100,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-05T09:30:00').toISOString(),
            notes: 'Initial stock receipt - Laptop Model X',
        },
        {
            productId: 2,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-001',
            quantityChange: 50,
            quantityAfter: 50,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-05T09:30:00').toISOString(),
            notes: 'Initial stock receipt - Wireless Mouse',
        },
        {
            productId: 3,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-001',
            quantityChange: 75,
            quantityAfter: 75,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-05T09:30:00').toISOString(),
            notes: 'Initial stock receipt - Mechanical Keyboard',
        },

        // Receipt REC-2024-002 entries (3 products)
        {
            productId: 4,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-002',
            quantityChange: 200,
            quantityAfter: 200,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-08T10:15:00').toISOString(),
            notes: 'Initial stock receipt - USB-C Cable',
        },
        {
            productId: 5,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-002',
            quantityChange: 150,
            quantityAfter: 150,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-08T10:15:00').toISOString(),
            notes: 'Initial stock receipt - HDMI Cable',
        },
        {
            productId: 1,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-002',
            quantityChange: 80,
            quantityAfter: 80,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-08T10:15:00').toISOString(),
            notes: 'Stock receipt - Laptop Model X',
        },

        // Receipt REC-2024-003 entries (3 products)
        {
            productId: 6,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-003',
            quantityChange: 120,
            quantityAfter: 120,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-12T14:20:00').toISOString(),
            notes: 'Initial stock receipt - External SSD',
        },
        {
            productId: 2,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-003',
            quantityChange: 100,
            quantityAfter: 150,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-12T14:20:00').toISOString(),
            notes: 'Restocking - Wireless Mouse',
        },
        {
            productId: 7,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-003',
            quantityChange: 90,
            quantityAfter: 90,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-12T14:20:00').toISOString(),
            notes: 'Initial stock receipt - Webcam HD',
        },

        // Receipt REC-2024-004 entries (3 products)
        {
            productId: 8,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-004',
            quantityChange: 60,
            quantityAfter: 60,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-15T11:00:00').toISOString(),
            notes: 'Initial stock receipt - USB Hub',
        },
        {
            productId: 3,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-004',
            quantityChange: 85,
            quantityAfter: 85,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-15T11:00:00').toISOString(),
            notes: 'Stock receipt - Mechanical Keyboard',
        },
        {
            productId: 4,
            warehouseId: 2,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-004',
            quantityChange: 150,
            quantityAfter: 350,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-15T11:00:00').toISOString(),
            notes: 'Restocking - USB-C Cable',
        },

        // Receipt REC-2024-005 entries (3 products)
        {
            productId: 9,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-005',
            quantityChange: 110,
            quantityAfter: 110,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-18T13:45:00').toISOString(),
            notes: 'Initial stock receipt - Monitor Stand',
        },
        {
            productId: 10,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-005',
            quantityChange: 95,
            quantityAfter: 95,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-18T13:45:00').toISOString(),
            notes: 'Initial stock receipt - Laptop Bag',
        },
        {
            productId: 1,
            warehouseId: 1,
            operationType: 'receipt',
            referenceNumber: 'REC-2024-005',
            quantityChange: 70,
            quantityAfter: 170,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-18T13:45:00').toISOString(),
            notes: 'Restocking - Laptop Model X',
        },

        // Delivery DEL-2024-001 entries (3 products)
        {
            productId: 1,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-001',
            quantityChange: -15,
            quantityAfter: 155,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-20T10:30:00').toISOString(),
            notes: 'Customer order - Tech Solutions Inc',
        },
        {
            productId: 2,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-001',
            quantityChange: -25,
            quantityAfter: 125,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-20T10:30:00').toISOString(),
            notes: 'Customer order - Tech Solutions Inc',
        },
        {
            productId: 3,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-001',
            quantityChange: -20,
            quantityAfter: 55,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-20T10:30:00').toISOString(),
            notes: 'Customer order - Tech Solutions Inc',
        },

        // Delivery DEL-2024-002 entries (2 products)
        {
            productId: 4,
            warehouseId: 2,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-002',
            quantityChange: -50,
            quantityAfter: 300,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-22T14:15:00').toISOString(),
            notes: 'Customer order - Digital World Ltd',
        },
        {
            productId: 5,
            warehouseId: 2,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-002',
            quantityChange: -30,
            quantityAfter: 120,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-22T14:15:00').toISOString(),
            notes: 'Customer order - Digital World Ltd',
        },

        // Delivery DEL-2024-003 entries (3 products)
        {
            productId: 6,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-003',
            quantityChange: -35,
            quantityAfter: 85,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-25T09:00:00').toISOString(),
            notes: 'Customer order - Enterprise Corp',
        },
        {
            productId: 7,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-003',
            quantityChange: -20,
            quantityAfter: 70,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-25T09:00:00').toISOString(),
            notes: 'Customer order - Enterprise Corp',
        },
        {
            productId: 9,
            warehouseId: 1,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-003',
            quantityChange: -15,
            quantityAfter: 95,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-25T09:00:00').toISOString(),
            notes: 'Customer order - Enterprise Corp',
        },

        // Delivery DEL-2024-004 entries (2 products)
        {
            productId: 8,
            warehouseId: 2,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-004',
            quantityChange: -18,
            quantityAfter: 42,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-28T11:45:00').toISOString(),
            notes: 'Customer order - Smart Office Co',
        },
        {
            productId: 1,
            warehouseId: 2,
            operationType: 'delivery',
            referenceNumber: 'DEL-2024-004',
            quantityChange: -12,
            quantityAfter: 68,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-01-28T11:45:00').toISOString(),
            notes: 'Customer order - Smart Office Co',
        },

        // Transfer TRF-2024-001 entries (3 products, 6 ledger entries)
        {
            productId: 1,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-001',
            quantityChange: -20,
            quantityAfter: 135,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 1,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-001',
            quantityChange: 20,
            quantityAfter: 88,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },
        {
            productId: 2,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-001',
            quantityChange: -30,
            quantityAfter: 95,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 2,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-001',
            quantityChange: 30,
            quantityAfter: 30,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },
        {
            productId: 3,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-001',
            quantityChange: -15,
            quantityAfter: 40,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 3,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-001',
            quantityChange: 15,
            quantityAfter: 100,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },

        // Transfer TRF-2024-002 entries (2 products, 4 ledger entries)
        {
            productId: 4,
            warehouseId: 2,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-002',
            quantityChange: -40,
            quantityAfter: 260,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-05T13:30:00').toISOString(),
            notes: 'Transfer to Warehouse 1',
        },
        {
            productId: 4,
            warehouseId: 1,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-002',
            quantityChange: 40,
            quantityAfter: 40,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-05T13:30:00').toISOString(),
            notes: 'Transfer from Warehouse 2',
        },
        {
            productId: 5,
            warehouseId: 2,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-002',
            quantityChange: -25,
            quantityAfter: 95,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-05T13:30:00').toISOString(),
            notes: 'Transfer to Warehouse 1',
        },
        {
            productId: 5,
            warehouseId: 1,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-002',
            quantityChange: 25,
            quantityAfter: 25,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-05T13:30:00').toISOString(),
            notes: 'Transfer from Warehouse 2',
        },

        // Transfer TRF-2024-003 entries (3 products, 6 ledger entries)
        {
            productId: 6,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-003',
            quantityChange: -25,
            quantityAfter: 60,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 6,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-003',
            quantityChange: 25,
            quantityAfter: 25,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },
        {
            productId: 7,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-003',
            quantityChange: -18,
            quantityAfter: 52,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 7,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-003',
            quantityChange: 18,
            quantityAfter: 18,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },
        {
            productId: 9,
            warehouseId: 1,
            operationType: 'transfer_out',
            referenceNumber: 'TRF-2024-003',
            quantityChange: -10,
            quantityAfter: 85,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer to Warehouse 2',
        },
        {
            productId: 9,
            warehouseId: 2,
            operationType: 'transfer_in',
            referenceNumber: 'TRF-2024-003',
            quantityChange: 10,
            quantityAfter: 10,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-10T15:00:00').toISOString(),
            notes: 'Transfer from Warehouse 1',
        },

        // Adjustment ADJ-2024-001 (shortage found)
        {
            productId: 2,
            warehouseId: 1,
            operationType: 'adjustment',
            referenceNumber: 'ADJ-2024-001',
            quantityChange: -3,
            quantityAfter: 92,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-12T16:30:00').toISOString(),
            notes: 'Physical count discrepancy - damaged items found',
        },

        // Adjustment ADJ-2024-002 (surplus found)
        {
            productId: 10,
            warehouseId: 1,
            operationType: 'adjustment',
            referenceNumber: 'ADJ-2024-002',
            quantityChange: 3,
            quantityAfter: 98,
            createdBy: 'user_placeholder_123',
            createdAt: new Date('2024-02-15T09:15:00').toISOString(),
            notes: 'Physical count discrepancy - extra items found in storage',
        },
    ];

    await db.insert(stockLedger).values(sampleStockLedger);
    
    console.log('✅ Stock ledger seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});